In [1]:
import torch

**Sigmoid activation Functtion** 
$$$
S(x) = \frac{1}{1+ e^{-x}}




In [2]:
#Sigmoid activation function
def activation (x):

    return 1/(1+torch.exp(-x))

In [3]:
#Some random data to build a NN model 
torch.manual_seed(10)

#features, weights and biases

x = torch.randn((1,5))

w = torch.randn_like(x)

b = torch.randn((1,1))

In [4]:
#Output y from wx + b

y = activation((x * w).sum() + b)

y

tensor([[0.9748]])

In [5]:
# Alternatively we can use tensor multiplication

y = activation (torch.mm(x, w.view(5,1)) + b)
y

tensor([[0.9748]])

In [6]:
# Dense layer with mulltilayer

# Generate Data

torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
x = torch.randn((1, 3))

# Define the size of each layer in our network
n_input = x.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units 
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer
w1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer
w2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
b1 = torch.randn((1, n_hidden))
b2 = torch.randn((1, n_output))

Calculate the output for this multi-layer network using the weights w1 & w2, and the biases, b1 & b2.

In [7]:
h = activation(torch.mm(x, w1) + b1)
y = activation(torch.mm(h, w2) + b2)
print(y)

tensor([[0.3171]])
